services:
  web:
    build: .
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HShop=Server=host.docker.internal,1433;Database=Hshop2023;User Id=sa;Password=123;TrustServerCertificate=True
